### ISSUE TITLE
updates from eventmachine-1.0.8

### ISSUE THREAD

**Issue by dtshepherd** [ibc/EventMachine-LE#33]
Do you plan to pull changes from eventmachine now that it has multiple new releases?

**Comment by ibc** [comment]
Honestly I do not have time enough now to manage this project.

**Comment by dtshepherd** [comment]
completely understand, maybe now that the eventmachine guys are doing updates, I can get them to add the ssl_version support.  We have some old web services we hit that won't work with the default version, always failing SSL handshake (server FIN).

**Comment by sodabrew** [comment]
Would you guys give the EventMachine 1.2.0.dev.2 gem a spin? It substantially incorporates the work from EventMachine-LE 1.1.x. I'd like to get some feedback before making a final 1.2.0 release.

**Comment by sodabrew** [comment]
EventMachine 1.2.0 has been released!

**Comment by dtshepherd** [comment]
Closing the issue since I've moved back to using EventMachine proper and its finally being maintained again.
